const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const home=$('#homeStage'),ritual=$('#ritualStage'),result=$('#resultStage'),scene=$('#ritualScene');
const wishDialog=$('#wishDialog'),input=$('#wishInput'),count=$('#count');
const holdBtn=$('#holdBtn'),holdFill=$('#holdFill'),progressText=$('#progressText');
const wishEcho=$('#wishEcho'),resultTitle=$('#resultTitle'),resultCopy=$('#resultCopy'),resultWish=$('#resultWish'),omenText=$('#omenText'),priceText=$('#priceText');
const USED='oneWishBranchPro.used.v1';
let lang='zh',wish='',holding=false,finished=false,start=0,raf=0,audioOn=false,audio=null;
const T={zh:{title:'一 愿 枝',subtitle:'你只有一次愿望',wish:'开始许愿',fiction:'虚构互动体验 · 结果仅供娱乐',ritual:'THE RITUAL',listen:'柳枝正在听',ritualHint:'长按中央，双手会拉开枝条。松手会重新开始。',hold:'按住 3 秒，折下此枝',release:'松手会重新开始',verdict:'THE VERDICT',copy:'复制结果',saveImage:'保存结果图',back:'返回首页',write:'写下你的愿望',warning:'写下后，仪式不会替你修改它。愿望将只属于这一次。',continue:'继续',resultTitle:'愿望已被听见',used:'这个浏览器已经许过一次愿。',copied:'已复制',omenLabel:'征兆',priceLabel:'代价'},en:{title:'ONE WISH',subtitle:'You only get one wish',wish:'BEGIN THE RITUAL',fiction:'Fictional interactive experience · For entertainment only',ritual:'THE RITUAL',listen:'The branch is listening',ritualHint:'Hold the center. Two hands will pull the branch apart. Release to begin again.',hold:'Hold for 3 seconds to break the branch',release:'Release to begin again',verdict:'THE VERDICT',copy:'COPY RESULT',saveImage:'SAVE RESULT IMAGE',back:'BACK HOME',write:'Write your wish',warning:'Once written, the ritual will not rewrite it for you.',continue:'CONTINUE',resultTitle:'Your wish has been heard',used:'This browser has already made its one wish.',copied:'Copied',omenLabel:'OMEN',priceLabel:'PRICE'}};
const P={zh:{a:['月色偏冷，说明这件事不能急于求成。','枝条发出清脆回响，说明这个愿望并非空想。','风向向内，答案更多藏在你自己手里。','今夜没有凶兆，只有提醒：愿望需要被照料。','叶脉发亮，象征机会会出现，但不是立刻。'],b:['先迈出最小的一步，它会比等待更有效。','把愿望拆成一个今天就能完成的动作。','先守住节奏，再谈结果。','让别人看见你的诚意，而不只是听见愿望。','在下一次犹豫之前，先替自己做一个清楚选择。'],c:['真正的代价不是失去，而是拖延。','它要求耐心，尤其在你最想立刻得到回应的时候。','不要把偶然的好转误认为终局。','放下对“完美时机”的迷信。','别让别人替你解释你的愿望。'],o:['月光偏盛','风势回旋','叶脉发亮','水声清晰','旧梦重现','雾气渐散'],p:['需要等待','需要行动','需要坦诚','需要克制','需要放下执念','需要重新排序']},en:{a:['The moon feels colder tonight. This cannot be rushed.','The branch answered clearly. This wish is not empty.','The wind turns inward. More of the answer is in your hands than in fate.','There is no bad omen tonight, only a reminder: a wish must be cared for.','The leaf veins glow. Opportunity may come, but not instantly.'],b:['Take the smallest concrete step first.','Turn the wish into one action you can complete today.','Protect your rhythm before chasing the result.','Let someone see your sincerity, not only hear your wish.','Before you hesitate again, make one clear choice.'],c:['The real cost is delay.','It asks for patience when you most want an immediate sign.','Do not mistake a brief improvement for the final outcome.','Let go of the myth of perfect timing.','Do not let others explain your wish for you.'],o:['The moon is strong','The wind circles back','Leaf veins are glowing','The water speaks clearly','An old dream returns','The fog is thinning'],p:['It needs waiting','It needs action','It needs honesty','It needs restraint','It needs release','It needs new priorities']}};
function stage(x){[home,ritual,result].forEach(s=>s.classList.toggle('active',s===x))}
function applyLang(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';$$('[data-i18n]').forEach(e=>{let k=e.dataset.i18n;if(T[lang][k])e.textContent=T[lang][k]});$('#langBtn').textContent=lang==='zh'?'EN':'中';$('#soundBtn').textContent=audioOn?'SOUND ON':'SOUND OFF';input.placeholder=lang==='zh'?input.dataset.placeholderZh:input.dataset.placeholderEn;$('#mainTitle').textContent=T[lang].title;$('#heroSubtitle').textContent=T[lang].subtitle;$('#wishBtn').textContent=T[lang].wish}
function hash(s){let h=2166136261;for(const ch of s){h^=ch.charCodeAt(0);h+=(h<<1)+(h<<4)+(h<<7)+(h<<8)+(h<<24)}return Math.abs(h>>>0)}
function verdict(w){const d=P[lang],h=hash(lang+'|'+w);return{body:[d.a[h%d.a.length],d.b[Math.floor(h/7)%d.b.length],d.c[Math.floor(h/13)%d.c.length]].join(' '),omen:d.o[Math.floor(h/17)%d.o.length],price:d.p[Math.floor(h/23)%d.p.length]}}
function reset(){scene.classList.remove('ready','broken');holdBtn.classList.remove('active');holdFill.style.right='100%';progressText.textContent=T[lang].release}
function sound(freq=330,d=.25){if(!audioOn)return;audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime;o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.05,n);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g).connect(audio.destination);o.start();o.stop(n+d)}
function begin(e){if(finished)return;e.preventDefault();holding=true;start=performance.now();scene.classList.add('ready');holdBtn.classList.add('active');sound(220,.2);cancelAnimationFrame(raf);raf=requestAnimationFrame(tick)}
function end(){if(finished)return;holding=false;cancelAnimationFrame(raf);reset()}
function tick(n){if(!holding)return;const p=Math.min(1,(n-start)/3000);holdFill.style.right=(100-p*100)+'%';progressText.textContent=(lang==='zh'?'仪式进行中 ':'Ritual in progress ')+Math.round(p*100)+'%';if(p>=1)return complete();raf=requestAnimationFrame(tick)}
function complete(){holding=false;finished=true;scene.classList.remove('ready');scene.classList.add('broken');holdBtn.classList.remove('active');holdFill.style.right='0%';navigator.vibrate?.([45,30,75]);sound(520,.8);const v=verdict(wish),rec={wish,...v,at:new Date().toISOString()};localStorage.setItem(USED,JSON.stringify(rec));setTimeout(()=>showResult(rec,false),1100)}
function showResult(r,used){wish=r.wish||'';resultTitle.textContent=used?T[lang].used:T[lang].resultTitle;resultCopy.textContent=r.body||verdict(wish||'wish').body;resultWish.textContent=wish?'“'+wish+'”':'';omenText.textContent=r.omen||P[lang].o[0];priceText.textContent=r.price||P[lang].p[0];stage(result)}
$('#langBtn').onclick=()=>{lang=lang==='zh'?'en':'zh';applyLang()};
$('#soundBtn').onclick=()=>{audioOn=!audioOn;$('#soundBtn').textContent=audioOn?'SOUND ON':'SOUND OFF';if(audioOn)sound(440,.4)};
$('#wishBtn').onclick=()=>{let r=null;try{r=JSON.parse(localStorage.getItem(USED)||'null')}catch{}if(r)return showResult(r,true);input.value='';count.textContent='0 / 120';wishDialog.showModal();setTimeout(()=>input.focus(),50)};
input.oninput=()=>count.textContent=input.value.length+' / 120';
$('#wishForm').onsubmit=e=>{const w=input.value.trim();if(!w){e.preventDefault();return input.focus()}wish=w;wishEcho.textContent='“'+wish+'”';finished=false;reset();stage(ritual)};
['pointerdown','touchstart'].forEach(x=>holdBtn.addEventListener(x,begin,{passive:false}));['pointerup','pointercancel','pointerleave','touchend','touchcancel'].forEach(x=>holdBtn.addEventListener(x,end,{passive:true}));
$('#homeBtn').onclick=()=>stage(home);
$('#shareBtn').onclick=async()=>{const text=[resultTitle.textContent,resultCopy.textContent,omenText.textContent+' / '+priceText.textContent,resultWish.textContent].join('\n');try{await navigator.clipboard.writeText(text);$('#shareBtn').textContent=T[lang].copied;setTimeout(()=>$('#shareBtn').textContent=T[lang].copy,1200)}catch{}};
$('#saveBtn').onclick=()=>{const c=document.createElement('canvas');c.width=1200;c.height=1500;const x=c.getContext('2d'),g=x.createRadialGradient(600,300,80,600,750,1000);g.addColorStop(0,'#18212c');g.addColorStop(1,'#050709');x.fillStyle=g;x.fillRect(0,0,1200,1500);x.strokeStyle='rgba(236,232,220,.12)';x.strokeRect(70,70,1060,1360);x.textAlign='center';x.fillStyle='#ece8dc';x.font='28px Arial';x.fillText('ONE WISH BRANCH · PRO',600,180);x.font='62px serif';x.fillText(resultTitle.textContent,600,300);wrap(x,resultCopy.textContent,600,430,850,54,'34px serif');x.font='24px Arial';x.fillText(T[lang].omenLabel+' · '+omenText.textContent,600,1030);x.fillText(T[lang].priceLabel+' · '+priceText.textContent,600,1080);x.font='34px serif';wrap(x,resultWish.textContent,600,1210,850,52,'34px serif');const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='one-wish-result.png';a.click()};
function wrap(ctx,text,cx,y,max,lineH,font){ctx.font=font;ctx.fillStyle='#ddd8cb';let line='',lines=[];for(const ch of text){const t=line+ch;if(ctx.measureText(t).width>max&&line){lines.push(line);line=ch}else line=t}if(line)lines.push(line);lines.forEach((l,i)=>ctx.fillText(l,cx,y+i*lineH))}
const sky=$('#sky'),embers=$('#embers'),sctx=sky.getContext('2d'),ectx=embers.getContext('2d');let stars=[],sparks=[],W=0,H=0,D=1;
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;[sky,embers].forEach(c=>{c.width=W*D;c.height=H*D;c.style.width=W+'px';c.style.height=H+'px'});sctx.setTransform(D,0,0,D,0,0);ectx.setTransform(D,0,0,D,0,0);stars=Array.from({length:Math.min(120,Math.floor(W/10))},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.5+.2,a:Math.random()*.6+.1,t:Math.random()*6.28}));sparks=Array.from({length:Math.min(70,Math.floor(W/15))},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()+.3,v:Math.random()*.2+.05,a:Math.random()*.25+.04}))}
function anim(){sctx.clearRect(0,0,W,H);stars.forEach(s=>{s.t+=.008;sctx.beginPath();sctx.fillStyle=`rgba(230,229,220,${s.a*(.7+.3*Math.sin(s.t))})`;sctx.arc(s.x,s.y,s.r,0,6.28);sctx.fill()});ectx.clearRect(0,0,W,H);sparks.forEach(p=>{p.y-=p.v;if(p.y<-4){p.y=H+4;p.x=Math.random()*W}ectx.beginPath();ectx.fillStyle=`rgba(224,208,156,${p.a})`;ectx.arc(p.x,p.y,p.r,0,6.28);ectx.fill()});requestAnimationFrame(anim)}
addEventListener('resize',resize,{passive:true});resize();anim();applyLang();
if(new URLSearchParams(location.search).get('reset')==='1'){localStorage.removeItem(USED)}
